### ISSUE TITLE
OpenGraph SSR support

### ISSUE THREAD

**Issue by gempir** [SevenTV/App#3]
You have OpenGraph already added but without server side rendering it becomes less effective.

Visiting only the source of this page without letting JS run will give you no opengraph tags.
https://7tv.app/emotes/6042af401d4963000d9dae36

I don't know how possible this is with your stack, if you only deploy a static html file to something like netlify it probably isn't very feasible, but I wanted to make an issue nonetheless.

**Comment by TroyDota** [comment]
@gempir A major problem blocking this issue from closing is that Discord refuses to animate any image that,
1. Does not end in `.gif`
2. Is not a gif.
Animated emotes will therefore not embed in Discord which is extremely annoying, rather the emote will just load indefinitely and timeout.
One solution is to convert the Animated WebP to a static image on the fly when requested so that Discord displays a static image but even this isnt trivial. Since Discord is wonky when it comes to how it requests the emote, so we cannot target JUST discord. And also it seems that Decoding Animated WebP has very little support. Everyone can encode it but it seems that the Decoding part is not very supported. I will likely have to implement an Animated WebP Decoder in Go, the only one that has worked is ImageMagic and well that doesn't meet the speed requirements.

**Comment by gempir** [comment]
I don't care about discord. If if it refuses to animate something that's a separate issue. OpenGraph Tags are useful for other applications as well.

**Comment by TroyDota** [comment]
Then this is already solved afaik.

**Comment by gempir** [comment]
It is
